### ISSUE TITLE
JQuery.Validation 1.8.1 throws error.  Update to 1.11

### ISSUE THREAD

**Issue by johndpalm** [rustd/AspnetIdentitySample#13]
Open project straight from github, go to Login page, click in username field:

Unhandled exception at line 1152, column 5 in http://localhost:26755/Scripts/jquery.validate.js

0x800a138f - JavaScript runtime error: Unable to get property 'call' of undefined or null reference

No error after update JQuery.Validation to 1.11.1

**Comment by rustd** [comment]
works fine for me. What browser were you using.....

**Comment by johndpalm** [comment]
IE 11 (8.1 Preview)

**Comment by ghost** [comment]
I had the same issue with IE11 RTM until I ran update-package.

**Comment by rustd** [comment]
hmm...I still dont see the error on the same config. Any possibility if you can upload your sample and update the repro steps with the exact set of steps

**Comment by johndpalm** [comment]
Honestly, I don't think it's worth anyone's time to try and analyze why this doesn't work with an old version of a 3rd party library. update-package, move on.

**Comment by JoshSimerman** [comment]
I downloaded the zip package just now, started fresh.

Do a build.

Change conn string in web.config so that the DB could be created.

 <connectionStrings>
    <add name="DefaultConnection" connectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\Identity5.mdf;Initial Catalog=Identity5;Integrated Security=True" providerName="System.Data.SqlClient" />
  </connectionStrings>

I get a javascript error when I click into the form field when trying to register.
0x800a138f - JavaScript runtime error: Unable to get property 'call' of undefined or null reference

Looking at packages.config, things are still RC, so run some nuget commands to update to RTM where needed.

update-package Microsoft.AspNet.Mvc
update-package Microsoft.jQuery.Unobtrusive.Ajax
update-package Microsoft.jQuery.Unobtrusive.Validation
update-package EntityFramework
update-package jQuery.Validation
